services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=template'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - "5430:5432"

    volumes:
      - '~/volumes/template/postgres:/var/lib/postgresql/data'
